import { useEffect, useMemo, useRef, useState } from "react";
import {
  Download,
  FileText,
  LoaderCircle,
  Scissors,
  Trash2,
  Upload,
  X,
} from "lucide-react";
import type { EditState, TimeRange } from "../../types";
import {
  transcribeVideo,
  TRANSCRIPTION_DOWNLOAD_MB,
} from "../../lib/transcription";
import { analyzeSilences } from "../../lib/audio-analysis";
import {
  cutTranscriptRanges,
  isFillerWord,
  selectionCuts,
  transcriptOccurrences,
  validateTranscript,
} from "../../lib/transcript-edit";
import type {
  TranscriptCut,
  TranscriptOccurrence,
} from "../../lib/transcript-edit";
import { downloadBlob } from "../../lib/media";
import "./transcript.css";

interface Props {
  blob: Blob;
  edits: EditState;
  duration: number;
  disabled: boolean;
  sourceTime: number;
  activeClipId: string;
  onChange: (edits: EditState) => void;
  onSeek: (clipId: string, time: number) => void;
  onBusyChange: (busy: boolean) => void;
  autoGenerate?: boolean;
  onAutoGenerated?: (edits: EditState) => void | Promise<void>;
}
const timeLabel = (time: number) =>
  `${Math.floor(time / 60)}:${(time % 60).toFixed(1).padStart(4, "0")}`;
const length = (clips: EditState["clips"]) =>
  clips.reduce((total, clip) => total + clip.end - clip.start, 0);

export default function TranscriptPanel({
  blob,
  edits,
  duration,
  disabled,
  sourceTime,
  activeClipId,
  onChange,
  onSeek,
  onBusyChange,
  autoGenerate = false,
  onAutoGenerated,
}: Props) {
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const [job, setJob] = useState<{
    stage: string;
    progress: number | null;
  } | null>(null);
  const [message, setMessage] = useState("");
  const [toolsOpen, setToolsOpen] = useState(!edits.transcript);
  const [error, setError] = useState("");
  const [silences, setSilences] = useState<TimeRange[] | null>(null);
  const [threshold, setThreshold] = useState(-40);
  const [minGap, setMinGap] = useState(0.5);
  const anchor = useRef<string | null>(null);
  const controller = useRef<AbortController | null>(null);
  const fileInput = useRef<HTMLInputElement>(null);
  const mounted = useRef(true);
  const autoStarted = useRef(false);
  const generateLatest = useRef<(automatic?: boolean) => void>(() => {});
  const busyCallback = useRef(onBusyChange);
  busyCallback.current = onBusyChange;
  const locked = disabled || !!job;
  const occurrences = useMemo(
    () => transcriptOccurrences(edits.clips, edits.transcript?.words ?? []),
    [edits.clips, edits.transcript],
  );
  const fillerOccurrences = useMemo(
    () =>
      occurrences.filter(
        (item) => item.end > item.start && isFillerWord(item.word.text),
      ),
    [occurrences],
  );

  useEffect(() => {
    setToolsOpen(!edits.transcript);
  }, [edits.transcript]);
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      controller.current?.abort();
      busyCallback.current(false);
    };
  }, []);
  useEffect(() => {
    const keys = new Set(occurrences.map((item) => item.key));
    setSelected((previous) => {
      const next = new Set([...previous].filter((key) => keys.has(key)));
      return next.size === previous.size ? previous : next;
    });
    if (anchor.current && !keys.has(anchor.current)) anchor.current = null;
  }, [occurrences]);

  async function run(
    stage: string,
    work: (
      signal: AbortSignal,
      progress: (value: { stage: string; progress: number | null }) => void,
    ) => Promise<void>,
    automatic = false,
  ) {
    if (locked || controller.current) return;
    const current = new AbortController();
    controller.current = current;
    setError("");
    setMessage("");
    setJob({ stage, progress: null });
    busyCallback.current(true);
    try {
      await work(current.signal, (value) => {
        if (mounted.current && !current.signal.aborted) setJob(value);
      });
    } catch (failure) {
      if (mounted.current) {
        if (
          current.signal.aborted ||
          (failure instanceof DOMException && failure.name === "AbortError")
        )
          setMessage(
            automatic
              ? "Transcription cancelled. Your recording is saved. You can generate its transcript whenever you’re ready."
              : "Cancelled. Your edits are unchanged.",
          );
        else
          setError(
            (failure instanceof Error
              ? failure.message
              : "This operation could not be completed. Please try again.") +
              (automatic ? " Your recording remains saved." : ""),
          );
      }
    } finally {
      if (controller.current === current) {
        controller.current = null;
        if (mounted.current) {
          setJob(null);
          busyCallback.current(false);
        }
      }
    }
  }

  function applyCuts(cuts: TranscriptCut[], description: string) {
    if (locked) return;
    if (cuts.length && cuts.every((cut) => cut.end === cut.start)) {
      setMessage(
        "Timing is unavailable for these words. Correct their start/end times in JSON, or include a neighboring word with timing in your selection.",
      );
      return;
    }
    try {
      const clips = cutTranscriptRanges(edits.clips, cuts);
      const removed = length(edits.clips) - length(clips);
      if (removed <= 0.000001) {
        setMessage("Nothing in the current timeline matches this selection.");
        return;
      }
      onChange({ ...edits, clips });
      setSelected(new Set());
      anchor.current = null;
      setSilences(null);
      setError("");
      setMessage(
        `${description}: ${removed.toFixed(2)} seconds removed. Use Undo edit to restore them.`,
      );
    } catch (failure) {
      setError(
        failure instanceof Error
          ? failure.message
          : "The selected time could not be removed.",
      );
    }
  }

  function selectWord(
    item: TranscriptOccurrence,
    shift: boolean,
    additive: boolean,
  ) {
    if (locked) return;
    onSeek(item.clipId, item.start);
    if (shift && anchor.current) {
      const from = occurrences.findIndex((word) => word.key === anchor.current);
      const to = occurrences.findIndex((word) => word.key === item.key);
      if (from >= 0) {
        const next = additive ? new Set(selected) : new Set<string>();
        occurrences
          .slice(Math.min(from, to), Math.max(from, to) + 1)
          .forEach((word) => next.add(word.key));
        setSelected(next);
        return;
      }
    }
    setSelected((previous) => {
      if (!additive) return new Set([item.key]);
      const next = new Set(previous);
      if (next.has(item.key)) next.delete(item.key);
      else next.add(item.key);
      return next;
    });
    anchor.current = item.key;
  }

  function generate(automatic = false) {
    if (locked || controller.current) return;
    if (autoGenerate) autoStarted.current = true;
    void run(
      "Preparing transcription",
      async (signal, onProgress) => {
        const transcript = await transcribeVideo(blob, { signal, onProgress });
        if (signal.aborted || !mounted.current) return;
        const next = {
          ...edits,
          // Recorder wall-clock duration may be a frame shorter than decoded
          // audio. Intersect generated timing with this source; JSON stays strict.
          transcript: validateTranscript(
            {
              ...transcript,
              words: transcript.words
                .filter(
                  (word) =>
                    !Number.isFinite(word.start) || word.start <= duration,
                )
                .map((word) => ({
                  ...word,
                  end: Number.isFinite(word.end)
                    ? Math.min(word.end, duration)
                    : word.end,
                })),
            },
            duration,
          ),
        };
        onChange(next);
        setSelected(new Set());
        if (automatic && onAutoGenerated) {
          onProgress({ stage: "Saving your transcript", progress: null });
          try {
            await onAutoGenerated(next);
          } catch (failure) {
            throw new Error(
              `The transcript is ready but could not be saved automatically. Use Save edits to try again. ${failure instanceof Error ? failure.message : ""}`.trim(),
            );
          }
          if (signal.aborted || !mounted.current) return;
        }
        setMessage(
          next.transcript.words.length
            ? "Transcript ready. Review the words and timing before making cuts."
            : "No speech words were detected. You can import a corrected transcript.",
        );
      },
      automatic,
    );
  }
  generateLatest.current = generate;

  useEffect(() => {
    if (
      !autoGenerate ||
      autoStarted.current ||
      edits.transcript ||
      locked ||
      duration <= 0 ||
      !Number.isFinite(duration)
    )
      return;
    // The first StrictMode effect is cleaned up before this runs. Consume the
    // attempt only when work actually starts, so setup/cleanup cannot duplicate it.
    const timer = window.setTimeout(() => {
      if (!mounted.current || autoStarted.current || controller.current) return;
      generateLatest.current(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [autoGenerate, edits.transcript, locked, duration]);

  function findSilences() {
    void run("Finding quiet sections", async (signal, onProgress) => {
      const ranges = await analyzeSilences(blob, {
        signal,
        onProgress,
        thresholdDb: threshold,
        minDuration: minGap,
        padding: 0.08,
      });
      if (signal.aborted || !mounted.current) return;
      const visible = ranges.filter((range) =>
        edits.clips.some(
          (clip) =>
            Math.min(clip.end, range.end) > Math.max(clip.start, range.start),
        ),
      );
      setSilences(visible);
      setMessage(
        visible.length
          ? "Review the quiet sections below, then apply the cuts."
          : "No quiet sections matched these settings in your timeline.",
      );
    });
  }

  const silencePreview = useMemo(() => {
    if (!silences?.length) return { removed: 0, error: "" };
    try {
      return {
        removed:
          length(edits.clips) -
          length(cutTranscriptRanges(edits.clips, silences)),
        error: "",
      };
    } catch (failure) {
      return {
        removed: 0,
        error:
          failure instanceof Error
            ? failure.message
            : "These cuts would remove the whole video.",
      };
    }
  }, [edits.clips, silences]);

  return (
    <section className="tp-panel" aria-label="Transcript editing">
      <div className="tp-heading">
        <FileText size={17} />
        <div>
          <h3>Edit the words. Make the cut.</h3>
          <p>English speech · processed on your device</p>
        </div>
      </div>
      <p className="tp-note">
        {edits.transcript
          ? "Review AI words and timing before cutting. Some fillers may be omitted."
          : "Generate a timed transcript, then select words to remove their footage. AI words and timing may need review; some fillers may be omitted."}
      </p>
      <details
        className="tp-tools"
        open={!edits.transcript || toolsOpen || !!job}
        onToggle={(event) => {
          if (edits.transcript && !job) setToolsOpen(event.currentTarget.open);
        }}
      >
        <summary>
          {edits.transcript ? "Transcript tools" : "Create your transcript"}
        </summary>
        <button
          className="ed-button ed-primary tp-wide"
          onClick={() => generate()}
          disabled={locked}
        >
          <FileText size={15} />
          {edits.transcript ? "Regenerate transcript" : "Generate transcript"}
        </button>
        <p className="tp-small">
          First use downloads about {TRANSCRIPTION_DOWNLOAD_MB} MB of speech
          model data plus its runtime. Internet is needed for that download.
          Your audio stays on this device. Supports videos up to 20 minutes and
          512 MB.
        </p>

        <div className="tp-file-actions">
          <button
            className="tp-text-button"
            disabled={locked}
            onClick={() => fileInput.current?.click()}
          >
            <Upload size={13} />
            Import JSON
          </button>
          <button
            className="tp-text-button"
            disabled={locked || !edits.transcript}
            onClick={() =>
              edits.transcript &&
              downloadBlob(
                new Blob([JSON.stringify(edits.transcript, null, 2)], {
                  type: "application/json",
                }),
                "frame-transcript.json",
              )
            }
          >
            <Download size={13} />
            Export JSON
          </button>
        </div>
        <input
          ref={fileInput}
          className="tp-file"
          type="file"
          accept=".json,application/json"
          aria-label="Import transcript JSON"
          onChange={(event) => {
            const file = event.target.files?.[0];
            event.target.value = "";
            if (!file) return;
            void run("Reading corrected transcript", async (signal) => {
              if (file.size > 8 * 1024 * 1024)
                throw new Error("Transcript JSON must be smaller than 8 MB.");
              let value: unknown;
              try {
                value = JSON.parse(await file.text());
              } catch {
                throw new Error(
                  "This is not valid JSON. Export a transcript to see the expected format.",
                );
              }
              const transcript = validateTranscript(value, duration);
              if (signal.aborted || !mounted.current) return;
              onChange({ ...edits, transcript });
              setSelected(new Set());
              setMessage(
                "Corrected transcript imported. Times use the original source video.",
              );
            });
          }}
        />
        <details className="tp-format">
          <summary>Correcting a transcript</summary>
          <p>
            Export JSON, correct its words or start/end times, then import it.
            Times are seconds in the original video. Keep unique word IDs and
            the language, model, and createdAt fields.
          </p>
        </details>
      </details>

      {job && (
        <div className="tp-progress" role="status">
          <div>
            <LoaderCircle size={14} className="ed-spin" />
            <span>{job.stage}</span>
            <button
              className="ed-icon"
              aria-label="Cancel transcript operation"
              disabled={job.stage === "Saving your transcript"}
              onClick={() => controller.current?.abort()}
            >
              <X size={15} />
            </button>
          </div>
          <progress
            max={1}
            value={job.progress ?? undefined}
            aria-label="Transcript operation progress"
          />
          <small>
            {job.progress === null
              ? "This may take a few minutes."
              : `${Math.round(job.progress * 100)}%`}
          </small>
        </div>
      )}
      {error && (
        <div className="tp-message tp-error" role="alert">
          {error}
          <button
            aria-label="Dismiss transcript error"
            onClick={() => setError("")}
          >
            <X size={13} />
          </button>
        </div>
      )}
      {message && (
        <p className="tp-message" role="status">
          {message}
        </p>
      )}

      {edits.transcript && (
        <>
          <div className="tp-transcript-heading">
            <strong>
              Transcript <span>{occurrences.length} words</span>
            </strong>
            <button
              className="tp-text-button"
              disabled={locked || !selected.size}
              onClick={() => {
                setSelected(new Set());
                anchor.current = null;
              }}
            >
              Clear selection
            </button>
          </div>
          <p className="tp-small">
            Click a word to select and seek. Shift-click selects a range;
            Ctrl/⌘-click adds words. Delete or Backspace makes the cut.
          </p>
          <div
            className="tp-words"
            role="group"
            aria-label="Transcript words"
            onKeyDown={(event) => {
              if (
                (event.key === "Delete" || event.key === "Backspace") &&
                selected.size &&
                !locked
              ) {
                event.preventDefault();
                event.stopPropagation();
                applyCuts(
                  selectionCuts(occurrences, selected),
                  "Selected words cut",
                );
              }
              if (event.key === "Escape") {
                setSelected(new Set());
                anchor.current = null;
              }
            }}
          >
            {occurrences.map((item, index) => (
              <span key={item.key}>
                {index === 0 ||
                occurrences[index - 1].clipId !== item.clipId ? (
                  <span className="tp-clip-label">
                    Clip{" "}
                    {edits.clips.findIndex((clip) => clip.id === item.clipId) +
                      1}{" "}
                    · {timeLabel(item.timelineStart)}
                  </span>
                ) : null}
                <button
                  type="button"
                  className={`tp-word ${selected.has(item.key) ? "is-selected" : ""} ${activeClipId === item.clipId && sourceTime >= item.start && sourceTime < item.end ? "is-current" : ""} ${isFillerWord(item.word.text) ? "is-filler" : ""}`}
                  disabled={locked}
                  aria-pressed={selected.has(item.key)}
                  aria-label={`${item.word.text}, clip ${edits.clips.findIndex((clip) => clip.id === item.clipId) + 1}, ${timeLabel(item.start)}${item.start === item.end ? ", timing unavailable" : ""}`}
                  title={
                    item.start === item.end
                      ? "Timing unavailable. Correct its timestamps or select it with a neighboring timed word."
                      : `${item.start.toFixed(2)}–${item.end.toFixed(2)}s in source`
                  }
                  onClick={(event) =>
                    selectWord(
                      item,
                      event.shiftKey,
                      event.ctrlKey || event.metaKey,
                    )
                  }
                >
                  {item.word.text}
                </button>{" "}
              </span>
            ))}
            {!occurrences.length && (
              <p className="tp-small">
                No transcript words remain in these clips.
              </p>
            )}
          </div>
          <button
            className="ed-button tp-wide"
            disabled={locked || !selected.size}
            onClick={() =>
              applyCuts(
                selectionCuts(occurrences, selected),
                "Selected words cut",
              )
            }
          >
            <Trash2 size={14} />
            Delete selected words{selected.size ? ` (${selected.size})` : ""}
          </button>
          <button
            className="ed-button tp-wide tp-filler-button"
            disabled={locked || !fillerOccurrences.length}
            onClick={() =>
              applyCuts(
                fillerOccurrences.map((item) => ({
                  clipId: item.clipId,
                  start: item.start,
                  end: item.end,
                })),
                "Filler words cut",
              )
            }
          >
            <Scissors size={14} />
            Remove filler words ({fillerOccurrences.length})
          </button>
          <p className="tp-small">
            Only exact “um”, “uh”, “erm”, “er”, and “hmm” are removed. “Like”
            and “so” stay. Every visible occurrence is included.
          </p>
        </>
      )}

      <section className="tp-silence" aria-label="Silence removal">
        <h3>Shorten the pauses</h3>
        <p className="tp-small">
          Find quiet audio in the source. Preview each section before cutting.
          Quiet speech can also fall below the threshold.
        </p>
        <label>
          Quiet threshold <span>{threshold} dB</span>
          <input
            type="range"
            min={-60}
            max={-20}
            step={1}
            value={threshold}
            disabled={locked}
            aria-label="Silence threshold in decibels"
            onChange={(event) => {
              setThreshold(Number(event.target.value));
              setSilences(null);
            }}
          />
        </label>
        <label>
          Minimum pause <span>{minGap.toFixed(1)}s</span>
          <input
            type="range"
            min={0.2}
            max={3}
            step={0.1}
            value={minGap}
            disabled={locked}
            aria-label="Minimum silence duration"
            onChange={(event) => {
              setMinGap(Number(event.target.value));
              setSilences(null);
            }}
          />
        </label>
        <button
          className="ed-button tp-wide"
          disabled={locked}
          onClick={findSilences}
        >
          <Scissors size={14} />
          Find silences
        </button>
        {silences && (
          <div className="tp-silence-results">
            <strong>
              {silences.length} quiet{" "}
              {silences.length === 1 ? "section" : "sections"}
              {silencePreview.removed > 0 &&
                ` · ${silencePreview.removed.toFixed(2)}s to cut`}
            </strong>
            {!!silences.length && (
              <ul aria-label="Silence preview">
                {silences.map((range, index) => (
                  <li key={`${range.start}-${range.end}`}>
                    <button
                      disabled={locked}
                      onClick={() => {
                        const clip = edits.clips.find(
                          (clip) =>
                            Math.min(clip.end, range.end) >
                            Math.max(clip.start, range.start),
                        );
                        if (clip)
                          onSeek(clip.id, Math.max(clip.start, range.start));
                      }}
                    >
                      Pause {index + 1}
                      <span>
                        {timeLabel(range.start)}–{timeLabel(range.end)}
                      </span>
                    </button>
                  </li>
                ))}
              </ul>
            )}
            {silencePreview.error && (
              <p className="tp-small tp-danger">{silencePreview.error}</p>
            )}
            <button
              className="ed-button tp-wide"
              disabled={locked || !silences.length || !!silencePreview.error}
              onClick={() => applyCuts(silences, "Quiet sections cut")}
            >
              Apply silence cuts
            </button>
            <p className="tp-small">
              Keeps 0.08s next to speech. Cuts apply to every matching clip
              occurrence; crop settings are preserved.
            </p>
          </div>
        )}
      </section>
    </section>
  );
}
